export {default as ConfirmPage} from './ConfirmPage'
export {default as InitialPage} from './InitialPage'
export {default as Profile} from './Profile'
export {default as RequestPage} from './RequestPage'
export {default as RegisterPage} from './RegisterPage'
export {default as LoginPage} from './LoginPage'
